apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/panicboat/kubernetes-manifests
    targetRevision: main
    path: argo-cd
    helm:
      valueFiles:
      - argo-cd/values/common.yaml
      - argo-cd/values/develop.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
