# GitOps事前準備: ローカルGiteaサーバー
# 使用方法: docker-compose up -d
# アクセス: http://localhost:3000
# 初期設定後、giteaadmin/admin123でログイン

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea-local
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "2222:22"
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=sqlite3
      - GITEA__security__SECRET_KEY=gitea-secret-key
      - GITEA__server__HTTP_PORT=3000
      - GITEA__server__DISABLE_SSH=false
      - GITEA__server__SSH_PORT=22
      - GITEA__service__DISABLE_REGISTRATION=false
      - INSTALL_LOCK=false
    volumes:
      - gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

volumes:
  gitea_data:
    driver: local
