apiVersion: v2
name: ingress-nginx
description: A Helm chart for ingress-nginx controller deployment
type: application
version: 0.1.0
appVersion: "1.9.4"

dependencies:
  - name: ingress-nginx
    version: "4.8.3"
    repository: "https://kubernetes.github.io/ingress-nginx"
