apiVersion: v2
name: ingress-nginx
description: NGINX Ingress Controller
type: application
version: 1.0.0
appVersion: "1.8.2"

dependencies:
- name: ingress-nginx
  version: "4.7.1"
  repository: "https://kubernetes.github.io/ingress-nginx"
