argo-cd:
  configs:
    cm:
      url: https://argocd.stg.panicboat.net

  controller:
    replicas: 1
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 400m
        memory: 384Mi

  server:
    replicas: 2
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 192Mi

    ingress:
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
        nginx.ingress.kubernetes.io/grpc-backend: "true"
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:region:account:certificate/staging-cert"
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
      hosts:
        - argocd.stg.panicboat.net
      tls:
        - secretName: argocd-server-tls-staging
          hosts:
            - argocd.stg.panicboat.net

  repoServer:
    replicas: 2
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 192Mi
