ingress-nginx:
  controller:
    replicaCount: 2

    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
        service.beta.kubernetes.io/aws-load-balancer-name: ingress-nginx-staging
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:region:account:certificate/staging-cert"
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"

    resources:
      requests:
        cpu: 100m
        memory: 90Mi
      limits:
        cpu: 800m
        memory: 384Mi

    config:
      ssl-redirect: "true"
      force-ssl-redirect: "true"
