apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.8.3"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  install:
    createNamespace: true
  targetNamespace: ingress-nginx
  values:
    # Global namespace override
    namespaceOverride: ingress-nginx
    controller:
      # Service configuration for Kind
      service:
        type: LoadBalancer

      # Host network configuration specific to Kind
      hostNetwork: false
      hostPort:
        enabled: true
        ports:
          http: 80
          https: 443

      # Resource limits optimized for local development
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi

      # Logging configuration
      config:
        log-level: "2"

      # Enable metrics collection for prometheus
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true

      # Disable admission webhooks to simplify local setup
      admissionWebhooks:
        enabled: false

    # Disable default backend to reduce resource usage
    defaultBackend:
      enabled: false